## Task 1
Data Cleaning Challenge on Sales Data.

In [1]:
import pandas as pd

In [2]:
Sales_Transactions_2017 = pd.read_csv("Sales Transactions-2017.csv")
Sales_Transactions_2018 = pd.read_csv("Sales Transactions-2018.csv")
Sales_Transactions_2019 = pd.read_csv("Sales Transactions-2019.csv")

In [3]:
Sales_Transactions_Updated = pd.concat([Sales_Transactions_2017,Sales_Transactions_2018,Sales_Transactions_2019])

In [4]:
Sales_Transactions_Updated

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [5]:
Sales_Transactions_Updated.shape

(111206, 9)

In [6]:
Sales_Transactions_Updated.dtypes

Date              object
Voucher           object
Party             object
Product           object
Qty               object
Rate              object
Gross             object
Disc              object
Voucher Amount    object
dtype: object

In [7]:
Sales_Transactions_Updated.isna().sum()

Date               12591
Voucher            12557
Party                 40
Product            12591
Qty                12557
Rate               12558
Gross              12558
Disc              105609
Voucher Amount     83646
dtype: int64

In [8]:
Sales_Transactions_edit = pd.read_csv("Sales-Transactions-Edited.csv")
Sales_Transactions_edit

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
95557,12/9/2019,4265,TP13,SPOON MED M.W,20,11.0
95558,12/9/2019,4266,K.SRIHARI,SMART BOUL(48),1,1830.0
95559,12/9/2019,4267,SMS,SMARTBOUL GLA(4000),1,1520.0
95560,12/9/2019,4268,ANILFANCY,RR WINEGLASS,100,20.0
95561,12/9/2019,4268,ANILFANCY,RR WATER GLASS,100,20.0

In [9]:
Sales_Transactions_edit.describe(include='all')

             Date       Voucher  Party   Product           Qty           Rate
count       95562  95562.000000  95562     95562  95562.000000   95561.000000
unique        835           NaN    712       866           NaN            NaN
top     5/17/2017           NaN   TP13  14 GREEN           NaN            NaN
freq          282           NaN  13056      2399           NaN            NaN
mean          NaN   4469.104006    NaN       NaN    182.157657     249.612310
std           NaN   2810.486250    NaN       NaN    725.256966    2013.475202
min           NaN      1.000000    NaN       NaN      0.000000       0.010000
25%           NaN   2047.000000    NaN       NaN     10.000000      16.000000
50%           NaN   4186.500000    NaN       NaN     50.000000      28.000000
75%           NaN   6854.000000    NaN       NaN    150.000000     140.000000
max           NaN  10042.000000    NaN       NaN  35000.000000  200000.000000

In [10]:
Sales_Transactions_edit.shape

(95562, 6)

In [11]:
Sales_Transactions_edit.isna().sum()

Date       0
Voucher    0
Party      0
Product    0
Qty        0
Rate       1
dtype: int64

In [12]:
Sales_Transactions_edit.dtypes

Date        object
Voucher      int64
Party       object
Product     object
Qty          int64
Rate       float64
dtype: object

In [13]:
Sales_Transactions_Updated.describe(include='all')

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
count,98615,98649,111166,98615,98649,98648,98648,5597,27560
unique,836,10044,1994,867,546,1109,2548,371,7149
top,,,TP13,,100,,,,
freq,3053,3053,13056,3053,12528,3051,3053,3053,3053

In [14]:
Sales_Transactions_Updated.nunique()

Date                836
Voucher           10044
Party              1994
Product             867
Qty                 546
Rate               1109
Gross              2548
Disc                371
Voucher Amount     7149
dtype: int64

In [15]:
Sales_Transactions_Updated.Qty

0                   2
1                   6
2                 500
3                   6
4                   5
             ...
19171             400
19172             NaN
19173             NaN
19174       99,284.90
19175    2,710,193.00
Name: Qty, Length: 111206, dtype: object

In [16]:
Sales_Transactions_Updated.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
19171    False
19172     True
19173     True
19174    False
19175    False
Length: 111206, dtype: bool

In [17]:
Sales_Transactions_Updated.shape

(111206, 9)

In [18]:
Sales_Transactions_Updated.drop_duplicates(inplace = True)

In [19]:
Sales_Transactions_Updated.shape

(96624, 9)

In [20]:
Sales_Transactions_edit.Product

0              DONA-VAI-9100
1            LITE FOAM(1200)
2          VISHNU CHOTA WINE
3            LITE FOAM(1200)
4              DONA-VAI-9100
                ...
95557          SPOON MED M.W
95558         SMART BOUL(48)
95559    SMARTBOUL GLA(4000)
95560           RR WINEGLASS
95561         RR WATER GLASS
Name: Product, Length: 95562, dtype: object

In [21]:
Sales_Transactions_edit.Voucher

0           1
1           1
2           2
3           2
4           2
         ...
95557    4265
95558    4266
95559    4267
95560    4268
95561    4268
Name: Voucher, Length: 95562, dtype: int64

In [22]:
Sales_Transactions_Updated["Voucher"] = Sales_Transactions_Updated["Voucher"].str.replace("Sal:","")

In [23]:
Sales_Transactions_Updated

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19169,10/10/2019,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",NaN,NaN
19170,10/10/2019,4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",NaN,NaN
19171,10/10/2019,4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [24]:
Sales_Transactions_Updated.dropna(subset=['Product'], inplace=True)

In [25]:
Sales_Transactions_Updated.isna().sum()

Date                  0
Voucher               0
Party                 0
Product               0
Qty                   0
Rate                  1
Gross                 1
Disc              92781
Voucher Amount    70814
dtype: int64

In [26]:
del Sales_Transactions_Updated["Disc"]

In [27]:
del Sales_Transactions_Updated["Voucher Amount"]

In [28]:
Sales_Transactions_Updated.describe()

         Date Voucher  Party   Product    Qty   Rate     Gross
count   96420   96420  96420     96420  96420  96419     96419
unique    836   10043   1835       867    512   1075      2514
top                     TP13  14 GREEN    100     26  2,600.00
freq     1133    1133  12818      2397  12459   2730      1458

In [29]:
Sales_Transactions_Updated

,Date,Voucher,Party,Product,Qty,Rate,Gross
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00"
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00"
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00"
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00"
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00"
...,...,...,...,...,...,...,...
19167,10/10/2019,4935,K.SRIHARI,16*20(100-W),140,26,"3,640.00"
19168,10/10/2019,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,"5,040.00"
19169,10/10/2019,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00"
19170,10/10/2019,4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00"
19171,10/10/2019,4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00"

In [30]:
Sales_Transactions_Updated.isna().sum()

Date       0
Voucher    0
Party      0
Product    0
Qty        0
Rate       1
Gross      1
dtype: int64

In [31]:
Sales_Transactions_Updated.dtypes

Date       object
Voucher    object
Party      object
Product    object
Qty        object
Rate       object
Gross      object
dtype: object

In [32]:
Sales_Transactions_Updated[Sales_Transactions_Updated['Rate'].isna()]

           Date Voucher     Party            Product Qty Rate Gross
43740  5/3/2018    9266  CUSTOMER  TIRML-BL-KG-17*23   2  NaN   NaN

In [33]:
Sales_Transactions_Updated.dropna(subset=['Rate'], inplace=True)

In [34]:
Sales_Transactions_Updated.isna().sum()

Date       0
Voucher    0
Party      0
Product    0
Qty        0
Rate       0
Gross      0
dtype: int64

In [35]:
Sales_Transactions_Updated.describe()

         Date Voucher  Party   Product    Qty   Rate     Gross
count   96419   96419  96419     96419  96419  96419     96419
unique    836   10043   1835       867    512   1075      2514
top                     TP13  14 GREEN    100     26  2,600.00
freq     1133    1133  12818      2397  12459   2730      1458

In [36]:
Sales_Transactions_edit.dtypes

Date        object
Voucher      int64
Party       object
Product     object
Qty          int64
Rate       float64
dtype: object

In [37]:
Sales_Transactions_Updated[Sales_Transactions_Updated["Gross"].astype(str).str.strip() == ""]

      Date Voucher                Party Product Qty Rate Gross
8                   khader vali late en
9                                   try
12                          DUMMY ENTRY
15                          dummy entry
96                               AUTOLO
...    ...     ...                  ...     ...  ..  ...   ...
18400                 suresh adurupalli
18585                           V.S.BAR
18622               markfed -adurupalli
19052                   8/10 late entry
19057                            10-Jul

[1133 rows x 7 columns]

In [38]:
Sales_Transactions_Updated["Voucher"] = (Sales_Transactions_Updated["Voucher"].str.strip().replace("", pd.NA))
Sales_Transactions_Updated["Qty"] = (Sales_Transactions_Updated["Qty"].str.strip().replace("", pd.NA))
Sales_Transactions_Updated["Rate"] = (Sales_Transactions_Updated["Rate"].str.strip().replace("", pd.NA))
Sales_Transactions_Updated["Gross"] = (Sales_Transactions_Updated["Gross"].str.strip().replace("", pd.NA))
Sales_Transactions_Updated["Date"] = (Sales_Transactions_Updated["Date"].str.strip().replace("", pd.NA))

In [39]:
Sales_Transactions_Updated

,Date,Voucher,Party,Product,Qty,Rate,Gross
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00"
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00"
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00"
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00"
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00"
...,...,...,...,...,...,...,...
19167,10/10/2019,4935,K.SRIHARI,16*20(100-W),140,26,"3,640.00"
19168,10/10/2019,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,"5,040.00"
19169,10/10/2019,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00"
19170,10/10/2019,4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00"
19171,10/10/2019,4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00"

In [40]:
Sales_Transactions_Updated.dropna(subset=['Voucher'], inplace = True)

In [41]:
Sales_Transactions_Updated

,Date,Voucher,Party,Product,Qty,Rate,Gross
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00"
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00"
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00"
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00"
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00"
...,...,...,...,...,...,...,...
19167,10/10/2019,4935,K.SRIHARI,16*20(100-W),140,26,"3,640.00"
19168,10/10/2019,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,"5,040.00"
19169,10/10/2019,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00"
19170,10/10/2019,4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00"
19171,10/10/2019,4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00"

In [42]:
Sales_Transactions_Updated["Rate"] = (Sales_Transactions_Updated["Rate"].str.replace(",", "").astype(float))

In [43]:
Sales_Transactions_Updated.dtypes

Date        object
Voucher     object
Party       object
Product     object
Qty         object
Rate       float64
Gross       object
dtype: object

In [44]:
Sales_Transactions_Updated["Gross"] = (Sales_Transactions_Updated["Gross"].str.replace(",", "").astype(float))

In [45]:
Sales_Transactions_Updated.dtypes

Date        object
Voucher     object
Party       object
Product     object
Qty         object
Rate       float64
Gross      float64
dtype: object

In [46]:
Sales_Transactions_Updated["Voucher"] = Sales_Transactions_Updated["Voucher"].astype(int)

In [47]:
Sales_Transactions_Updated.dtypes

Date        object
Voucher      int64
Party       object
Product     object
Qty         object
Rate       float64
Gross      float64
dtype: object

In [48]:
Sales_Transactions_Updated["Qty"] = (Sales_Transactions_Updated["Qty"].str.replace(",", "").astype(float))
Sales_Transactions_Updated["Qty"] = Sales_Transactions_Updated["Qty"].astype(int)

In [49]:
Sales_Transactions_Updated.dtypes

Date        object
Voucher      int64
Party       object
Product     object
Qty          int64
Rate       float64
Gross      float64
dtype: object

In [50]:
Sales_Transactions_Updated["Date"].dtype

dtype('O')

In [51]:
Sales_Transactions_Updated["Date"] = pd.to_datetime(Sales_Transactions_Updated["Date"],dayfirst=True)

In [52]:
Sales_Transactions_Updated

,Date,Voucher,Party,Product,Qty,Rate,Gross
0,2017-04-01,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0,3380.0
1,2017-04-01,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0,9720.0
2,2017-04-01,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0,11500.0
3,2017-04-01,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0,9720.0
4,2017-04-01,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0,8450.0
...,...,...,...,...,...,...,...
19167,2019-10-10,4935,K.SRIHARI,16*20(100-W),140,26.0,3640.0
19168,2019-10-10,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,5040.0
19169,2019-10-10,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0,5120.0
19170,2019-10-10,4935,K.SRIHARI,10*12 RK,800,8.5,6800.0
19171,2019-10-10,4935,K.SRIHARI,13*16 WHITE RK,400,16.0,6400.0

In [53]:
Sales_Transactions_Updated.dtypes

Date       datetime64[ns]
Voucher             int64
Party              object
Product            object
Qty                 int64
Rate              float64
Gross             float64
dtype: object

In [54]:
Sales_Transactions_Updated.isna().sum()

Date       0
Voucher    0
Party      0
Product    0
Qty        0
Rate       0
Gross      0
dtype: int64

In [55]:
Sales_Transactions_Updated.to_csv("Sales_Transactions_Updated.csv")

## Task 2
Merge Function 1 Example

In [56]:
Student_Details = {
    "Stu_ID": [101, 102, 103, 105, 106],
    "Name": ["Jeeva", "Raj", "Ramu", "Gugan", "Harry"]
}
Student_Marks_Details = {
    "Stu_ID": [101, 102, 105, 108, 109],
    "Math_Marks": [89, 78, 82, 76, 74]
}
Stu_Data = pd.DataFrame({"Name": ["Jeeva", "Raj"]})
Stu_Mark = pd.DataFrame({"Subject": ["Maths", "Science", "English"]})

In [57]:
Student = pd.DataFrame(Student_Details)
Marks = pd.DataFrame(Student_Marks_Details)

Student_Result_Inner = pd.merge(Student, Marks, on = "Stu_ID", how = 'inner')
Student_Result_Outer = pd.merge(Student, Marks, on = "Stu_ID", how = 'outer')
Student_Result_Left = pd.merge(Student, Marks, on = "Stu_ID", how = 'left')
Student_Result_Right = pd.merge(Student, Marks, on = "Stu_ID", how = 'right')

print('\n',Student_Result_Inner)
print('\n',Student_Result_Outer)
print('\n',Student_Result_Left)
print('\n',Student_Result_Right)

    Stu_ID   Name  Math_Marks
0     101  Jeeva          89
1     102    Raj          78
2     105  Gugan          82

    Stu_ID   Name  Math_Marks
0     101  Jeeva        89.0
1     102    Raj        78.0
2     103   Ramu         NaN
3     105  Gugan        82.0
4     106  Harry         NaN
5     108    NaN        76.0
6     109    NaN        74.0

    Stu_ID   Name  Math_Marks
0     101  Jeeva        89.0
1     102    Raj        78.0
2     103   Ramu         NaN
3     105  Gugan        82.0
4     106  Harry         NaN

    Stu_ID   Name  Math_Marks
0     101  Jeeva          89
1     102    Raj          78
2     105  Gugan          82
3     108    NaN          76
4     109    NaN          74

In [58]:
Details = pd.merge(Stu_Data, Stu_Mark, how="cross")
print(Details)

    Name  Subject
0  Jeeva    Maths
1  Jeeva  Science
2  Jeeva  English
3    Raj    Maths
4    Raj  Science
5    Raj  English

## Task 3
List Comprehension 2 examples

In [59]:
Numbers = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
Even_Number = [x for x in Numbers if x % 2 == 0]
Odd_Number = [x for x in Numbers if x % 2 != 0]
print("Odd Number - ",Odd_Number)
print("Even Number - ",Even_Number)

Odd Number -  [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
Even Number -  [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [60]:
Odd_Number, Even_Number = ([x for x in Numbers if x % 2 != 0],[x for x in Numbers if x % 2 == 0])
print("Odd Number - ",Odd_Number)
print("Even Number - ",Even_Number)

Odd Number -  [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
Even Number -  [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [61]:
Prime_Number = [x for x in Numbers if x > 1 and all(x % i != 0 for i in range(2, x))]
NonPrime_Number = [x for x in Numbers if x <= 1 or any(x % i == 0 for i in range(2, x))]
print("Prime Number - ",Prime_Number)
print("Non Prime Number - ",NonPrime_Number)

Prime Number -  [2, 3, 5, 7, 11, 13, 17, 19]
Non Prime Number -  [1, 4, 6, 8, 9, 10, 12, 14, 15, 16, 18, 20]

## Task 4
Lambda Function 2 examples with Map, Filter, Reduce

In [62]:
Odd_Number = list(filter(lambda x : x % 2 != 0, Numbers))
Even_Number = list(filter(lambda x : x % 2 == 0, Numbers))
print("Odd Number - ",Odd_Number)
print("Even Number - ",Even_Number)

Odd Number -  [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
Even Number -  [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [63]:
Odd_Even_Result = list(map(lambda x: "{} is Even".format(x) 
                           if x % 2 == 0 else "{} is Odd".format(x), Numbers))
print(Odd_Even_Result)

['1 is Odd', '2 is Even', '3 is Odd', '4 is Even', '5 is Odd', '6 is Even', '7 is Odd', '8 is Even', '9 is Odd', '10 is Even', '11 is Odd', '12 is Even', '13 is Odd', '14 is Even', '15 is Odd', '16 is Even', '17 is Odd', '18 is Even', '19 is Odd', '20 is Even']

In [64]:
from functools import reduce
Sum_result_Odd = reduce(lambda x,y : x+y, Odd_Number)
Sum_result_Even = reduce(lambda x,y : x+y, Even_Number)
print(Sum_result_Odd)
print(Sum_result_Even)

100
110

In [65]:
Sum_result_Odd = reduce(lambda x,y : x+y, list(filter(lambda x : x % 2 != 0, Numbers)))
Sum_result_Even = reduce(lambda x,y : x+y, list(filter(lambda x : x % 2 == 0, Numbers)))
print(Sum_result_Odd)
print(Sum_result_Even)

100
110

In [66]:
Prime_Number = list(filter(lambda x: x > 1 and all(x % i != 0 for i in range(2, x)),Numbers)) 
NonPrime_Number = list(filter(lambda x: x <= 1 or any(x % i == 0 for i in range(2, x)),Numbers)) 
print("Prime Number - ",Prime_Number) 
print("Non Prime Number - ",NonPrime_Number)

Prime Number -  [2, 3, 5, 7, 11, 13, 17, 19]
Non Prime Number -  [1, 4, 6, 8, 9, 10, 12, 14, 15, 16, 18, 20]

In [67]:
Prime_NonPrime_Result = list(map(lambda x: "{} is Prime".format(x)
                                 if all(x % i != 0 for i in range(2, x))
                                 else "{} is Non-Prime".format(x), Numbers))
print(Prime_NonPrime_Result)

['1 is Prime', '2 is Prime', '3 is Prime', '4 is Non-Prime', '5 is Prime', '6 is Non-Prime', '7 is Prime', '8 is Non-Prime', '9 is Non-Prime', '10 is Non-Prime', '11 is Prime', '12 is Non-Prime', '13 is Prime', '14 is Non-Prime', '15 is Non-Prime', '16 is Non-Prime', '17 is Prime', '18 is Non-Prime', '19 is Prime', '20 is Non-Prime']

In [68]:
Prime_Sum = reduce(lambda x,y : x+y, Prime_Number)
NonPrime_Sum = reduce(lambda x,y : x+y, NonPrime_Number)
print(Prime_Sum)
print(NonPrime_Sum)

77
133

In [69]:
Prime_Sum = reduce(lambda x, y: x + y, (list(filter(lambda x: x > 1 and all(x % i != 0 for i in range(2, x)),Numbers))))
NonPrime_Sum = reduce(lambda x, y: x + y, (list(filter(lambda x: x <= 1 or any(x % i == 0 for i in range(2, x)),Numbers))))
print(Prime_Sum)
print(NonPrime_Sum)

77
133