## Task 2
Create 3 DataFrames using Dictionaries

In [1]:
import pandas as pd
Student_Data = {
    "Student Name":["Jeeva","Raj","Ramu","Somu","Harry"],
    "Subject":["Tamil","English","Maths","Science","Social"],
    "Marks":[88,77,22,99,78]
}

pd.DataFrame(Student_Data)

  Student Name  Subject  Marks
0        Jeeva    Tamil     88
1          Raj  English     77
2         Ramu    Maths     22
3         Somu  Science     99
4        Harry   Social     78

In [2]:
Student_Mark_Data = {
    "Student Name":["Jeeva","Raj","Ramu","Somu","Harry"],
    "Tamil":[88,77,89,76,84],
    "English":[86,73,78,79,77],
    "Maths":[93,85,87,81,88],
    "Science":[94,77,93,79,83],
    "Social":[89,84,79,89,88]
}

pd.DataFrame(Student_Mark_Data)

  Student Name  Tamil  English  Maths  Science  Social
0        Jeeva     88       86     93       94      89
1          Raj     77       73     85       77      84
2         Ramu     89       78     87       93      79
3         Somu     76       79     81       79      89
4        Harry     84       77     88       83      88

In [3]:
Student_Data = {
    "Student Name": ["Jeeva", "Raj", "Ramu", "Somu", "Harry"],
    "Age": [20, 21, 20, 22, 21],
    "City": ["Chennai", "Erode", "Salem", "Chennai", "Coimbatore"]
}

print(pd.DataFrame(Student_Data))
pd.DataFrame(Student_Data)

  Student Name  Age        City
0        Jeeva   20     Chennai
1          Raj   21       Erode
2         Ramu   20       Salem
3         Somu   22     Chennai
4        Harry   21  Coimbatore

  Student Name  Age        City
0        Jeeva   20     Chennai
1          Raj   21       Erode
2         Ramu   20       Salem
3         Somu   22     Chennai
4        Harry   21  Coimbatore

In [4]:
Student_Results = {
    "Student Name": ["Jeeva", "Raj", "Ramu", "Somu", "Harry"],
    "Total Marks": [466, 454, 240, 387, 403],
    "Result": ["Pass", "Pass", "Fail", "Pass", "Pass"]
}

pd.DataFrame(Student_Results)

  Student Name  Total Marks Result
0        Jeeva          466   Pass
1          Raj          454   Pass
2         Ramu          240   Fail
3         Somu          387   Pass
4        Harry          403   Pass

In [5]:
def student_data():
    Student_Data = {
    "Student Name": ["Jeeva", "Raj", "Ramu", "Somu", "Harry"],
    "Age": [20, 21, 20, 22, 21],
    "City": ["Chennai", "Erode", "Salem", "Chennai", "Coimbatore"]
    }
    print('\n',pd.DataFrame(Student_Data))

def student_mark_data():
    Student_Mark_Data = {
    "Student Name":["Jeeva","Raj","Ramu","Somu","Harry"],
    "Tamil":[88,77,89,76,84],
    "English":[86,73,78,79,77],
    "Maths":[93,85,87,81,88],
    "Science":[94,77,93,79,83],
    "Social":[89,84,79,89,88]
    }
    print('\n',pd.DataFrame(Student_Mark_Data))

def student_results():
    Student_Results = {
    "Student Name": ["Jeeva", "Raj", "Ramu", "Somu", "Harry"],
    "Total Marks": [466, 454, 240, 387, 403],
    "Result": ["Pass", "Pass", "Fail", "Pass", "Pass"]
    }
    print('\n',pd.DataFrame(Student_Results))

User_Choice = input("""\nPlease type '1' if you want to see Student Details\n
Please type '2' if you want to see Student Marks\n
Please type '3' if you want to see Student Results """)

if User_Choice == "1":
    student_data()

elif User_Choice == "2":
    student_mark_data()

elif User_Choice == "3":
    student_results()

else:
    print("Invaild input!!")

Please type '1' if you want to see Student Details

Please type '2' if you want to see Student Marks

Please type '3' if you want to see Student Results  3

   Student Name  Total Marks Result
0        Jeeva          466   Pass
1          Raj          454   Pass
2         Ramu          240   Fail
3         Somu          387   Pass
4        Harry          403   Pass